apiVersion: v2
name: cnpg-cluster
description: Create postgres tenant clusters managed by the CNPG Operator
type: application
version: 1.0.2

dependencies:
  - name: cluster
    alias: cnpgCluster
    version: 0.5.0
    repository: https://cloudnative-pg.github.io/charts
    condition: cnpgCluster.enabled

maintainers:
  - name: "cloudymax"
    url: "https://cloudydev.net"
  - name: "jessebot"
    url: "https://jessebot.work"
