apiVersion: v2
name: cnpg-cluster
description: Create postgres tenant clusters managed by the CNPG Operator
type: application
version: 0.6.0

maintainers:
  - name: "cloudymax"
    url: "https://github.com/cloudymax"
  - name: "jessebot"
    url: "https://jessebot.work"
